environment:
  PSGalleryKey:
    secure: PnXPcVJqKA84pb+5SE15noCZ3neiHmrJgsvLJeyIkbIHW4rQwJ5vYK7U6T3th8iv

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

build: false

test_script:
  - ps: . .\build.ps1

on_success:
  - ps: . .\build.ps1 -task deploy