environment:
  PSGalleryKey:
    secure: PnXPcVJqKA84pb+5SE15noCZ3neiHmrJgsvLJeyIkbIHW4rQwJ5vYK7U6T3th8iv

configuration: Release

build: false

before_test:
  - ps: Install-Module Pester
  - ps: Install-Module Psake

test_script:
  - ps: Invoke-PSake
  - ps: if($psake.build_success -eq $false){throw 'build failed.'}